<?php
include('config/config.php');
include('PHPMailer/src/SMTP.php');
include('PHPMailer/src/PHPMailer.php');
require('PHPMailer/src/Exception.php');
$mail = new PHPMailer\PHPMailer\PHPMailer();
if (isset($_POST['resetpwd'])) {
    
    //prevent posting blank value for email
    if (isset($_POST['email']) && !empty($_POST['email'])) {
      $user_email = mysqli_real_escape_string($conn, trim($_POST['email']));
    } else {
      $error = 1;
      $err = "Enter your E-mail";
    }
  $email = $_POST['email'];
    // check if the user exists
    $query = mysqli_query($conn, "SELECT * from `user` WHERE email='" . $email . "'");
    $num_rows = mysqli_num_rows($query);
  
    if ($num_rows > 0) // check if alredy liked or not condition
    {
      $n = date('y');
      $password = bin2hex(random_bytes($n));
      $new_password=substr($password,0,10);
      //Insert Captured information to a database table
      $query = "UPDATE user SET  password=? WHERE  email =?";
      $stmt = $conn->prepare($query);
      //bind paramaters
      $rc = $stmt->bind_param('ss', $new_password, $email);
      $stmt->execute();

$mail->setFrom('companyemail@gmail.com');
$mail->addAddress($email);
$mail->Subject ='E-house Password Reset confirmation';
$mail->Body = '<h2 style="color:Black;">Here is Password Reset</h2>
<p style="color:Blue;">Here is your new password  '.$new_password.' . After login in your can change it.</p>';

$mail->isHTML(true);
$mail->AltBody = "This message is generated by plain text !";
$mail->IsSMTP();
$mail->SMTPSecure = 'ssl';
$mail->Host = 'ssl://smtp.gmail.com';
$mail->SMTPAuth = true;
$mail->Port = 465;
$mail->Username = 'companyemail@gmail.com';
$mail->Password = 'passwod';
if(!$mail->send()) {
  echo 'Email is not sent.';
  echo 'Email error: ' . $mail->ErrorInfo;
} else {
  
  echo"<script>alert('Please check your Reset password in your email');</script>";
  
}
}
}
?>


<!DOCTYPE html>
<html lang="en">
    <!--Head-->
    <?php require_once("partials/head.php");?>
    <!-- ./ Head -->
    <body class="form no-image-content">
        <div class="form-container outer">
            <div class="form-form">
                <div class="form-form-wrap">
                    <div class="form-container">
                        <div class="form-content">
                            <h1 class="">Password Recovery</h1>
                            <p class="signup-link recovery">Enter your email and instructions will sent to you!</p>
                            <form class="text-left" method="post">
                                <div class="form">
                                    <div id="email-field" class="field-wrapper input">
                                        <div class="d-flex justify-content-between">
                                            <label for="email">EMAIL</label>
                                        </div>
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-at-sign"><circle cx="12" cy="12" r="4"></circle><path d="M16 8v5a3 3 0 0 0 6 0v-1a10 10 0 1 0-3.92 7.94"></path></svg>
                                        <input id="email" name="email" type="text" class="form-control" value="" placeholder="Email">
                                    </div>

                                    <div class="d-sm-flex justify-content-between">

                                        <div class="field-wrapper">
                                            <button type="submit" name ="resetpwd" class="btn btn-primary" value="">Reset</button>
                                        </div>
                                    </div>

                                </div>
                            </form>

                        </div>                    
                    </div>
                </div>
            </div>
        </div>   
    <!-- BEGIN GLOBAL MANDATORY SCRIPTS -->
    <script src="assets/js/libs/jquery-3.1.1.min.js"></script>
    <script src="bootstrap/js/popper.min.js"></script>
    <script src="bootstrap/js/bootstrap.min.js"></script>
    
    <!-- END GLOBAL MANDATORY SCRIPTS -->
    <script src="assets/js/authentication/form-2.js"></script>

</body>
</html>