<?php
include('config/config.php');
include('../PHPMailer/src/SMTP.php');
include('../PHPMailer/src/PHPMailer.php');
require('../PHPMailer/src/Exception.php');
$mail = new PHPMailer\PHPMailer\PHPMailer();
if (isset($_POST['resetpwd'])) {

    //prevent posting blank value for email
    if (isset($_POST['admin_email']) && !empty($_POST['admin_email'])) {
        $admin_email = mysqli_real_escape_string($conn, trim($_POST['admin_email']));
    } else {
        $error = 1;
        $err = "Enter your E-mail";
    }
    $admin_email = $_POST['admin_email'];
    // check if the user exists
    $query = mysqli_query($conn, "SELECT * from `liteERP_admin` WHERE admin_email='" . $admin_email . "'");
    $num_rows = mysqli_num_rows($query);



    if ($num_rows > 0) // check if alredy liked or not condition
    {
        $n = date('y');
        $password = bin2hex(random_bytes($n));
        $new_password = substr($password, 0, 10);
        //Insert Captured information to a database table
        $query = "UPDATE liteERP_admin SET  admin_password=? WHERE  admin_email =?";
        $stmt = $conn->prepare($query);
        //bind paramaters
        $rc = $stmt->bind_param('ss', $new_password, $admin_email);
        $stmt->execute();
        //Get company email and password
        $ret = "SELECT * FROM  liteERP_settings ";
        $stmt = $conn->prepare($ret);
        // $stmt->bind_param('i', $admin_id);
        $stmt->execute();
        $res = $stmt->get_result();
        while ($credentials = $res->fetch_object()) {
            $name = $credentials->erp_name;
            $logo = $credentials->erp_logo;
            $email = $credentials->erp_email;
            $password = $credentials->erp_email_password;
            $mail->setFrom($email);
            $mail->addAddress($admin_email);
            $mail->AddEmbeddedImage('assets/img/' . $logo . '', 'logo');

            $mail->Subject = '' . $name . '  Password Reset confirmation';
            $mail->Body = '
<img src="cid:logo">
<h2 style="color:Black;">Here is Password Reset</h2>
<p style="color:Blue;">Here is your new password  ' . $new_password . ' . After login in your can change it.</p>
';

            $mail->isHTML(true);
            $mail->AltBody = "This message is generated by plain text !";
            $mail->IsSMTP();
            $mail->SMTPSecure = 'ssl';
            $mail->Host = 'ssl://smtp.gmail.com';
            $mail->SMTPAuth = true;
            $mail->Port = 465;
            $mail->Username = $email;
            $mail->Password = $password;
            if (!$mail->send()) {
                $error = 1;
                $error = 'Email error: ' . $mail->ErrorInfo;
            } else {

                $success = "Please check your Reset password in your email" && header("refresh:1; url=admin_reset_pwd.php");
            }
        }
    }
}
?>


<!DOCTYPE html>
<html lang="en">
<!--Head-->
<?php require_once("partials/head.php"); ?>
<!-- ./ Head -->

<body class="form no-image-content">
    <div class="form-container outer">
        <div class="form-form">
            <div class="form-form-wrap">
                <div class="form-container">
                    <div class="form-content">
                        <h1 class="">Password Recovery</h1>
                        <p class="signup-link recovery">Enter your email and instructions will sent to you!</p>
                        <form class="text-left" method="post">
                            <div class="form">
                                <div id="email-field" class="field-wrapper input">
                                    <div class="d-flex justify-content-between">
                                        <label for="email">EMAIL</label>
                                    </div>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-at-sign">
                                        <circle cx="12" cy="12" r="4"></circle>
                                        <path d="M16 8v5a3 3 0 0 0 6 0v-1a10 10 0 1 0-3.92 7.94"></path>
                                    </svg>
                                    <input id="email" name="admin_email" type="text" class="form-control" value="" placeholder="Email">
                                </div>

                                <div class="d-sm-flex justify-content-between">

                                    <div class="field-wrapper">
                                        <button type="submit" name="resetpwd" class="btn btn-primary" value="">Reset</button>
                                    </div>
                                </div>

                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php require_once('partials/scripts.php'); ?>
</body>

</html>